spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/patrickpulfer/TUS-Microservices-Assignment
          clone-on-start: true
          default-label: main
          skip-ssl-validation=true: